# backend/services/coco_service.py

from pathlib import Path


def build_coco_from_detections(detections_per_image, categories, images_root):
    """
    Convert YOLO detection results into clean COCO-style JSON.
    """

    coco = {
        "info": {
            "description": "Auto-generated by IndiaAnnotate",
            "version": "1.0",
            "year": 2025,
            "license": {"name": "MIT"}
        },
        "images": [],
        "annotations": [],
        "categories": categories
    }

    annotation_id = 1
    image_id = 1

    for img in detections_per_image:

        img_path = Path(img["image_path"])

        # ---- SAFER RELATIVE PATH HANDLING ----
        try:
            file_name = img_path.relative_to(images_root).as_posix()
        except Exception:
            file_name = img_path.name

        # IMAGE ENTRY
        coco["images"].append({
            "id": image_id,
            "file_name": file_name,
            "width": img["width"],
            "height": img["height"]
        })

        # ANNOTATIONS
        for obj in img["objects"]:
            x, y, w, h = obj["bbox"]

            coco["annotations"].append({
                "id": annotation_id,
                "image_id": image_id,
                "category_id": obj["category_id"],
                "bbox": [float(x), float(y), float(w), float(h)],
                "area": float(w * h),
                "iscrowd": 0,
                "segmentation": [],        # <-- REQUIRED FOR COCO
                "score": obj["score"]
            })

            annotation_id += 1

        image_id += 1

    return coco
