# utils/coco_builder.py
from pathlib import Path

def build_coco_from_detections(detections_per_image, categories, images_root):
    """
    Convert YOLO detection results into COCO-style JSON.

    detections_per_image = [
        {
            "image_path": "...",
            "width": ...,
            "height": ...,
            "objects": [
                {
                    "category_id": ...,
                    "bbox": [...],
                    "score": ...
                }
            ]
        }
    ]

    categories = [
        {"id": 1, "name": "person", "supercategory": "object"},
        ...
    ]
    """

    coco = {
        "info": {
            "description": "Auto-generated by IndiaAnnotate",
            "version": "1.0",
            "year": 2025
        },
        "categories": categories,
        "images": [],
        "annotations": []
    }

    annotation_id = 1
    image_id = 1

    for img in detections_per_image:
        # BUILD IMAGE ENTRY
        coco["images"].append({
            "id": image_id,
            "file_name": Path(img["image_path"]).relative_to(images_root).as_posix(),
            "width": img["width"],
            "height": img["height"]
        })

        # BUILD ANNOTATIONS
        for obj in img["objects"]:
            coco["annotations"].append({
                "id": annotation_id,
                "image_id": image_id,
                "category_id": obj["category_id"],
                "bbox": obj["bbox"],
                "area": obj["bbox"][2] * obj["bbox"][3],
                "iscrowd": 0,
                "score": obj["score"]
            })
            annotation_id += 1

        image_id += 1

    return coco
